version: '3'
services:
  mosquitto:
    image: alez/mosquitto-raspi
#@sha256:74cf253803b484a12b8db2a1744f51f2768eeae68da4c363613d91946495497d
    ports:
    - "1883:1883"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
         condition: none
      placement:
        constraints: [node.labels.alessandro-VirtualBox2==true]
