version: '3'
services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    deploy:
       mode: global
       restart_policy:
         condition: none
       placement:
         constraints: [node.role == worker]

  mosquitto:
    image: toke/mosquitto
    ports:
    - "1883:1883"
    deploy:
      mode: global
      restart_policy:
         condition: none
      placement:
        constraints: [node.role == worker]

  test-app:
    image: alez/test-app
    deploy:
      mode: global
      restart_policy:
         condition: none
      placement:
        constraints: [node.role == worker]
