version: '3'
services:
  mongo:
    image: alez/mongo-raspi:3
    ports:
    - "27017:27017"
    deploy:
       mode: replicated
       replicas: 1
       restart_policy:
         condition: none
       placement:
         constraints:
         - node.labels.bar2==baz2
