version: '3'
services:
  mongo:
    image: mongo
    ports:
    - "127.0.0.1:27017:27017"
    deploy:
       mode: replicated
       placement:
         constraints: [node.role==worker]

  mosquitto:
    image: toke/mosquitto
    ports:
    - "1883:1883"
    deploy:
      mode: replicated
      placement:
         constraints: [node.role==worker]
